apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base/
patchesStrategicMerge:
- deployment.yaml
- service.yaml

replicas:
  - name: vote
    count: 8

images:
  - name: schoolofdevops/vote
    newTag: v4

namespace: instavote

commonLabels:
  project: instavote
  env: staging

commonAnnotations:
  supported-by: "contact@email.com"

configMapGenerator:
  - name: vote-options
    env: options.env
